const express = require('express');
const healthRoutes = require('./health.routes');
const authRoutes = require('./authRoutes');
const testRoutes = require('./testRoutes');
const userRoutes = require('./userRoutes');
const sellerRoutes = require('./sellerRoutes');
const adminSellerRoutes = require('./adminSellerRoutes');
const adminCategoryRoutes = require('./adminCategoryRoutes');
const categoryRoutes = require('./categoryRoutes');
const sellerProductRoutes = require('./sellerProductRoutes');
const productRoutes = require('./productRoutes');
const cartRoutes = require('./cartRoutes');
const orderRoutes = require('./orderRoutes');
const paymentRoutes = require('./paymentRoutes');
const shippingRoutes = require('./shippingRoutes');
const sellerDashboardRoutes = require('./sellerDashboardRoutes');
const adminDashboardRoutes = require('./adminDashboardRoutes');
const adminUserRoutes = require('./adminUserRoutes');
const adminSellerManagementRoutes = require('./adminSellerManagementRoutes');
const adminProductRoutes = require('./adminProductRoutes');
const adminOrderRoutes = require('./adminOrderRoutes');
const adminPlatformFeeRoutes = require('./adminPlatformFeeRoutes');
const adminAnalyticsRoutes = require('./adminAnalyticsRoutes');
const adminAuditRoutes = require('./adminAuditRoutes');
const adminFinanceRoutes = require('./adminFinanceRoutes');
const sellerReturnRoutes = require('./sellerReturnRoutes');
const adminReturnRoutes = require('./adminReturnRoutes');
const notificationRoutes = require('./notificationRoutes');
const reviewRoutes = require('./reviewRoutes');
const sellerReviewRoutes = require('./sellerReviewRoutes');
const adminReviewRoutes = require('./adminReviewRoutes');
const wishlistRoutes = require('./wishlistRoutes');
const adminCouponRoutes = require('./adminCouponRoutes');
const couponRoutes = require('./couponRoutes');
const recommendationRoutes = require('./recommendationRoutes');
const sellerInventoryRoutes = require('./sellerInventoryRoutes');
const adminInventoryRoutes = require('./adminInventoryRoutes');
const sellerFulfillmentRoutes = require('./sellerFulfillmentRoutes');
const adminFulfillmentRoutes = require('./adminFulfillmentRoutes');
const adminShipmentRoutes = require('./adminShipmentRoutes');
const sellerWalletRoutes = require('./sellerWalletRoutes');
const adminPayoutRoutes = require('./adminPayoutRoutes');
const supportRoutes = require('./supportRoutes');
const adminSupportRoutes = require('./adminSupportRoutes');
const sellerSupportRoutes = require('./sellerSupportRoutes');

const sellerAnalyticsRoutes = require('./sellerAnalyticsRoutes');
const adminReportRoutes = require('./adminReportRoutes');
const sellerReportRoutes = require('./sellerReportRoutes');

const router = express.Router();

// Register v1 routes
router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/test', testRoutes);
router.use('/users', userRoutes);
router.use('/seller/dashboard', sellerDashboardRoutes);
router.use('/seller/products', sellerProductRoutes);
router.use('/seller/inventory', sellerInventoryRoutes);
router.use('/seller/fulfillments', sellerFulfillmentRoutes);
router.use('/seller/returns', sellerReturnRoutes);
router.use('/seller/reviews', sellerReviewRoutes);
router.use('/seller/wallet', sellerWalletRoutes);
router.use('/seller/support', sellerSupportRoutes);
router.use('/seller/analytics', sellerAnalyticsRoutes);
router.use('/seller/reports', sellerReportRoutes);
router.use('/seller', sellerRoutes);

router.use('/admin/dashboard', adminDashboardRoutes);
router.use('/admin/users', adminUserRoutes);
router.use('/admin/sellers', adminSellerManagementRoutes);
router.use('/admin/seller-applications', adminSellerRoutes);
router.use('/admin/categories', adminCategoryRoutes);
router.use('/admin/products', adminProductRoutes);
router.use('/admin/orders', adminOrderRoutes);
router.use('/admin/fulfillments', adminFulfillmentRoutes);
router.use('/admin/shipments', adminShipmentRoutes);
router.use('/admin/returns', adminReturnRoutes);
router.use('/admin/reviews', adminReviewRoutes);
router.use('/admin/platform-fees', adminPlatformFeeRoutes);
router.use('/admin/analytics', adminAnalyticsRoutes);
router.use('/admin/reports', adminReportRoutes);
router.use('/admin/audit-logs', adminAuditRoutes);
router.use('/admin/finance', adminFinanceRoutes);
router.use('/admin/coupons', adminCouponRoutes);
router.use('/admin/inventory', adminInventoryRoutes);
router.use('/admin/payouts', adminPayoutRoutes);
router.use('/admin/support', adminSupportRoutes);

router.use('/support', supportRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/recommendations', recommendationRoutes);
router.use('/reviews', reviewRoutes);
router.use('/cart', cartRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/coupons', couponRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/shipping', shippingRoutes);
router.use('/notifications', notificationRoutes);

module.exports = router;
